version: '3'
services:
  frontend:
    image: frontend-image:latest
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000
  backend:
    image: backend-image:latest
    ports:
      - '5000:5000'